<?php
// SPDX-License-Identifier: EUPL-1.2
// Textes bilingues (le français fait foi).

return [
    'back_to_form' => ['fr' => 'Revenir au formulaire', 'en' => 'Back to the form'],
    'notfound_title' => ['fr' => 'Page introuvable', 'en' => 'Page not found'],
    'notfound' => ['fr' => 'Cette adresse n’existe pas. Le formulaire de signature se trouve sur la page d’accueil de ce site.', 'en' => 'This address does not exist. The signature form is on the home page of this site.'],
    'site_url' => ['fr' => 'https://www.otspi.org/', 'en' => 'https://www.otspi.org/en/'],
    'home_alt' => ['fr' => 'OTSPI — retour au site', 'en' => 'OTSPI — back to the website'],
    'manifesto_url' => ['fr' => 'https://www.otspi.org/manifeste.html', 'en' => 'https://www.otspi.org/en/manifesto.html'],
    'manifesto_link' => ['fr' => 'Lire le manifeste', 'en' => 'Read the manifesto'],
    'legal_url' => ['fr' => 'https://www.otspi.org/mentions-legales.html', 'en' => 'https://www.otspi.org/en/legal-notice.html'],
    'legal_link' => ['fr' => 'Mentions légales', 'en' => 'Legal notice'],
    'title' => ['fr' => 'Signer le manifeste', 'en' => 'Sign the manifesto'],
    'heading' => ['fr' => 'Signer le manifeste pour une identité numérique libre et ouverte', 'en' => 'Sign the manifesto for a free and open digital identity'],
    'firstname' => ['fr' => 'Prénom', 'en' => 'First name'],
    'lastname' => ['fr' => 'Nom', 'en' => 'Last name'],
    'email' => ['fr' => 'Adresse e-mail (jamais publiée)', 'en' => 'E-mail address (never published)'],
    'position' => ['fr' => 'Fonction (facultatif)', 'en' => 'Position (optional)'],
    'organisation' => ['fr' => 'Organisation (facultatif)', 'en' => 'Organisation (optional)'],
    'publish' => [
        'fr' => 'J’accepte que mon nom, ma fonction et mon organisation apparaissent dans la liste publique des signataires.',
        'en' => 'I agree that my name, position and organisation appear in the public list of signatories.',
    ],
    'submit' => ['fr' => 'Signer', 'en' => 'Sign'],
    'privacy' => [
        'fr' => 'Données collectées : prénom, nom, adresse e-mail et, facultativement, fonction et organisation. Finalités : enregistrer votre signature, la vérifier et, avec votre accord et après un contrôle destiné à écarter les usurpations d’identité, la publier. Base légale : votre consentement, retirable à tout moment. L’adresse e-mail n’est jamais publiée. Une demande non confirmée est supprimée sous 7 jours ; les signatures sont conservées pendant la campagne puis au plus deux ans après sa clôture. Responsable du traitement : Philippe Vienne, membre fondateur de l’initiative OTSPI, jusqu’à la constitution de l’association. Hébergement : o2switch (France). Contact et exercice de vos droits : contact@otspi.org.',
        'en' => 'Data collected: first name, last name, e-mail address and, optionally, position and organisation. Purposes: recording your signature, verifying it and, with your consent and after a check intended to rule out impersonation, publishing it. Legal basis: your consent, which may be withdrawn at any time. Your e-mail address is never published. An unconfirmed request is deleted within 7 days; signatures are kept during the campaign and then for at most two years after it closes. Data controller: Philippe Vienne, founding member of the OTSPI initiative, until the association is formed. Hosting: o2switch (France). Contact and exercise of your rights: contact@otspi.org.',
    ],
    'err_invalid' => ['fr' => 'Certains champs sont manquants ou invalides. Vérifiez le prénom, le nom et l’adresse e-mail ; les liens ne sont pas acceptés.', 'en' => 'Some fields are missing or invalid. Please check your first name, last name and e-mail address; links are not accepted.'],
    'err_pow' => ['fr' => 'La vérification anti-robot n’a pas abouti. Rechargez la page et réessayez ; JavaScript doit être activé.', 'en' => 'The anti-bot check did not complete. Reload the page and try again; JavaScript must be enabled.'],
    'err_disposable' => ['fr' => 'Les adresses e-mail jetables ne sont pas acceptées : utilisez une adresse durable, qui vous permettra aussi de retirer votre signature.', 'en' => 'Disposable e-mail addresses are not accepted: please use a lasting address, which will also let you withdraw your signature.'],
    'pow_wait' => ['fr' => 'Vérification anti-robot en cours, un instant…', 'en' => 'Anti-bot check in progress, one moment…'],
    'pow_error' => ['fr' => 'Ce navigateur ne permet pas la vérification anti-robot. Écrivez à contact@otspi.org pour signer.', 'en' => 'This browser cannot run the anti-bot check. Write to contact@otspi.org to sign.'],
    'noscript' => ['fr' => 'JavaScript est nécessaire pour la vérification anti-robot (calcul dans votre navigateur, sans service tiers). Sans JavaScript, écrivez à contact@otspi.org pour signer.', 'en' => 'JavaScript is required for the anti-bot check (computed in your browser, with no third-party service). Without JavaScript, write to contact@otspi.org to sign.'],
    'err_form' => ['fr' => 'Le formulaire a expiré ou a été envoyé trop vite. Rechargez la page et réessayez.', 'en' => 'The form has expired or was sent too fast. Reload the page and try again.'],
    'err_rate' => ['fr' => 'Trop de tentatives. Réessayez plus tard.', 'en' => 'Too many attempts. Please try again later.'],
    'err_mail' => ['fr' => 'L’e-mail de confirmation n’a pas pu être envoyé. Réessayez plus tard ou écrivez à contact@otspi.org.', 'en' => 'The confirmation e-mail could not be sent. Try again later or write to contact@otspi.org.'],
    'sent_title' => ['fr' => 'Vérifiez votre boîte de réception', 'en' => 'Check your inbox'],
    'sent' => [
        'fr' => 'Si l’adresse est valide, un e-mail de confirmation vient d’être envoyé. Votre signature ne sera enregistrée qu’après avoir cliqué sur le lien qu’il contient (valable 48 heures). Pensez à regarder vos courriers indésirables.',
        'en' => 'If the address is valid, a confirmation e-mail has just been sent. Your signature will only be recorded once you click the link it contains (valid for 48 hours). Please also check your spam folder.',
    ],
    'confirmed_title' => ['fr' => 'Signature confirmée', 'en' => 'Signature confirmed'],
    'confirmed' => [
        'fr' => 'Merci, votre signature est enregistrée. Si vous avez accepté sa publication, elle apparaîtra dans la liste des signataires après vérification. Un e-mail vous a été envoyé avec sa preuve horodatée et un lien pour la retirer.',
        'en' => 'Thank you, your signature is recorded. If you agreed to its publication, it will appear in the list of signatories once checked. An e-mail has been sent to you with its timestamped proof and a link to withdraw it.',
    ],
    'confirm_title' => ['fr' => 'Confirmer ma signature', 'en' => 'Confirm my signature'],
    'confirm_ask' => ['fr' => 'Dernière étape : vérifiez les informations ci-dessous puis cliquez sur le bouton pour confirmer votre signature du manifeste. Si elles ne sont pas les vôtres, fermez cette page : rien ne sera enregistré.', 'en' => 'Last step: check the information below, then click the button to confirm your signature of the manifesto. If it is not yours, close this page: nothing will be recorded.'],
    'confirm_button' => ['fr' => 'Confirmer ma signature', 'en' => 'Confirm my signature'],
    'err_server_title' => ['fr' => 'Erreur temporaire', 'en' => 'Temporary error'],
    'err_server' => ['fr' => 'Une erreur inattendue est survenue. Réessayez dans quelques minutes ou écrivez à contact@otspi.org.', 'en' => 'An unexpected error occurred. Try again in a few minutes or write to contact@otspi.org.'],
    'confirm_invalid_title' => ['fr' => 'Lien invalide ou expiré', 'en' => 'Invalid or expired link'],
    'confirm_invalid' => ['fr' => 'Ce lien n’est plus valide. Vous pouvez signer à nouveau depuis le formulaire.', 'en' => 'This link is no longer valid. You can sign again using the form.'],
    'withdraw_title' => ['fr' => 'Retirer ma signature', 'en' => 'Withdraw my signature'],
    'withdraw_ask' => ['fr' => 'Confirmez-vous le retrait de votre signature et la suppression de vos données ?', 'en' => 'Do you confirm withdrawing your signature and deleting your data?'],
    'withdraw_button' => ['fr' => 'Retirer et supprimer mes données', 'en' => 'Withdraw and delete my data'],
    'withdrawn_title' => ['fr' => 'Signature retirée', 'en' => 'Signature withdrawn'],
    'withdrawn' => ['fr' => 'Votre signature et vos données ont été supprimées. Le retrait de la liste publique est effectif au prochain rafraîchissement du site (sous 24 heures).', 'en' => 'Your signature and your data have been deleted. Removal from the public list takes effect at the next refresh of the website (within 24 hours).'],
    'mail_confirm_subject' => ['fr' => 'Confirmez votre signature du manifeste OTSPI', 'en' => 'Confirm your signature of the OTSPI manifesto'],
    // Pas de nom en tête de message : les champs saisis ne figurent que dans le récapitulatif, présenté
    // comme tel, pour que le site ne serve pas à faire parvenir un texte libre à une adresse quelconque.
    'mail_confirm_body' => [
        'fr' => "Bonjour,\n\nUne demande de signature du manifeste pour une identité numérique libre et ouverte a été faite avec cette adresse e-mail et les informations suivantes :\n\n%s\n\nSi elles sont exactes, ouvrez ce lien (valable 48 heures) puis cliquez sur le bouton de confirmation :\n\n%s\n\nSi vous n'êtes pas à l'origine de cette demande ou si ces informations ne sont pas les vôtres, ignorez ce message : rien ne sera enregistré.\n\nOTSPI — contact@otspi.org",
        'en' => "Hello,\n\nA request to sign the manifesto for a free and open digital identity was made with this e-mail address and the following information:\n\n%s\n\nIf it is correct, open this link (valid for 48 hours) and click the confirmation button:\n\n%s\n\nIf you did not make this request or this information is not yours, ignore this message: nothing will be recorded.\n\nOTSPI — contact@otspi.org",
    ],
    'recap_firstname' => ['fr' => 'Prénom', 'en' => 'First name'],
    'recap_lastname' => ['fr' => 'Nom', 'en' => 'Last name'],
    'recap_position' => ['fr' => 'Fonction', 'en' => 'Position'],
    'recap_organisation' => ['fr' => 'Organisation', 'en' => 'Organisation'],
    'recap_publish' => ['fr' => 'Nom publié dans la liste des signataires', 'en' => 'Name published in the list of signatories'],
    'yes' => ['fr' => 'oui', 'en' => 'yes'],
    'no' => ['fr' => 'non', 'en' => 'no'],
    'mail_done_subject' => ['fr' => 'Votre signature du manifeste OTSPI est enregistrée', 'en' => 'Your signature of the OTSPI manifesto is recorded'],
    'mail_done_body' => [
        'fr' => "Bonjour,\n\nMerci : votre signature est enregistrée.\n\nSa preuve horodatée, que vous pouvez vérifier vous-même (attestation et jeton d'horodatage RFC 3161, émis par le service d'horodatage d'OTSPI en démonstration, sans valeur juridique) :\n\n%2\$s\n\nPour retirer votre signature et supprimer vos données à tout moment, utilisez ce lien :\n\n%1\$s\n\nOTSPI — contact@otspi.org",
        'en' => "Hello,\n\nThank you: your signature is recorded.\n\nIts timestamped proof, which you can verify yourself (attestation and RFC 3161 timestamp token, issued by OTSPI's timestamping service in demonstration, with no legal value):\n\n%2\$s\n\nTo withdraw your signature and delete your data at any time, use this link:\n\n%1\$s\n\nOTSPI — contact@otspi.org",
    ],
    'mail_proof_subject' => ['fr' => 'Votre signature du manifeste OTSPI est désormais horodatée', 'en' => 'Your signature of the OTSPI manifesto is now timestamped'],
    'mail_proof_body' => [
        'fr' => "Bonjour,\n\nVotre signature du manifeste pour une identité numérique libre et ouverte est désormais horodatée par le service d'horodatage qu'OTSPI construit, en démonstration (sans valeur juridique). Voici sa preuve, que vous pouvez vérifier vous-même (attestation et jeton RFC 3161) :\n\n%s\n\nPour retirer votre signature, utilisez le lien reçu lors de sa confirmation ou écrivez à contact@otspi.org.\n\nOTSPI — contact@otspi.org",
        'en' => "Hello,\n\nYour signature of the manifesto for a free and open digital identity is now timestamped by the timestamping service OTSPI is building, in demonstration (with no legal value). Here is its proof, which you can verify yourself (attestation and RFC 3161 token):\n\n%s\n\nTo withdraw your signature, use the link you received when confirming it or write to contact@otspi.org.\n\nOTSPI — contact@otspi.org",
    ],
    'proof_title' => ['fr' => 'Preuve de signature', 'en' => 'Proof of signature'],
    'proof_invalid' => ['fr' => 'Ce lien de preuve ne correspond à aucune signature : elle a peut-être été retirée.', 'en' => 'This proof link matches no signature: it may have been withdrawn.'],
    'proof_ok' => ['fr' => 'Horodatage vérifié', 'en' => 'Timestamp verified'],
    'proof_pending' => ['fr' => 'Horodatage en cours : la preuve sera disponible sous 24 heures au plus.', 'en' => 'Timestamping in progress: the proof will be available within 24 hours.'],
    'proof_error' => ['fr' => 'Le jeton d’horodatage n’a pas pu être vérifié. Écrivez à contact@otspi.org.', 'en' => 'The timestamp token could not be verified. Write to contact@otspi.org.'],
    'proof_intro' => [
        'fr' => 'Cette signature du manifeste pour une identité numérique libre et ouverte a été confirmée par son auteur, puis horodatée par une autorité d’horodatage (RFC 3161). Le jeton porte sur l’empreinte de l’attestation ci-dessous : la modifier, même d’un caractère, le rend invalide.',
        'en' => 'This signature of the manifesto for a free and open digital identity was confirmed by its author, then timestamped by a timestamping authority (RFC 3161). The token covers the fingerprint of the attestation below: changing it, even by one character, invalidates it.',
    ],
    'proof_timestamp' => ['fr' => 'Horodatage', 'en' => 'Timestamp'],
    'proof_date' => ['fr' => 'Date certifiée', 'en' => 'Certified date'],
    'proof_digest' => ['fr' => 'Empreinte SHA-256 de l’attestation', 'en' => 'SHA-256 fingerprint of the attestation'],
    'proof_serial' => ['fr' => 'Numéro de série du jeton', 'en' => 'Token serial number'],
    'proof_unit' => ['fr' => 'Unité d’horodatage', 'en' => 'Timestamping unit'],
    'proof_issuer' => ['fr' => 'Émise par', 'en' => 'Issued by'],
    'proof_policy' => ['fr' => 'Politique (OID)', 'en' => 'Policy (OID)'],
    'proof_checks' => ['fr' => 'Contrôles effectués par ce site', 'en' => 'Checks performed by this site'],
    'proof_check_signature' => ['fr' => 'Signature de l’unité d’horodatage valide (CMS, RFC 5652)', 'en' => 'Valid timestamping unit signature (CMS, RFC 5652)'],
    'proof_check_digest' => ['fr' => 'Le jeton porte sur l’empreinte exacte de l’attestation', 'en' => 'The token covers the exact fingerprint of the attestation'],
    'proof_check_chain' => ['fr' => 'Certificat d’horodatage (usage « Time Stamping ») émis par l’autorité épinglée par ce site', 'en' => 'Timestamping certificate (“Time Stamping” usage) issued by the authority pinned by this site'],
    'proof_self' => ['fr' => 'Vérifier vous-même', 'en' => 'Verify it yourself'],
    'proof_download_json' => ['fr' => 'Attestation (.json)', 'en' => 'Attestation (.json)'],
    'proof_download_tsr' => ['fr' => 'Jeton d’horodatage (.tsr)', 'en' => 'Timestamp token (.tsr)'],
    'proof_demo' => [
        'fr' => 'Sur la démonstration d’OTSPI, onglet « Vérifier », déposez ensemble l’attestation et le jeton : la vérification se fait entièrement dans votre navigateur.',
        'en' => 'On the OTSPI demonstration, “Verify” tab, drop the attestation and the token together: verification runs entirely in your browser.',
    ],
    'proof_demo_link' => ['fr' => 'Ouvrir le vérificateur', 'en' => 'Open the verifier'],
    'proof_openssl' => ['fr' => 'Ou avec OpenSSL, après avoir téléchargé la chaîne de l’autorité :', 'en' => 'Or with OpenSSL, after downloading the authority’s chain:'],
    'proof_chain_link' => ['fr' => 'Chaîne de certificats de l’autorité (.pem)', 'en' => 'Authority certificate chain (.pem)'],
    'proof_staging' => [
        'fr' => 'Autorité de démonstration (staging) : ce jeton n’est pas qualifié au sens du règlement eIDAS et n’a aucune valeur juridique. Il montre le fonctionnement du service d’horodatage qu’OTSPI construit.',
        'en' => 'Demonstration authority (staging): this token is not qualified under the eIDAS regulation and has no legal value. It shows how the timestamping service OTSPI is building works.',
    ],
];
